name: Chapolin execuion 🧪
on: [push]
jobs:
  chapolin-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: node chapolin.js
        uses: node chapolin.js